### PR TITLE
Responsive contact page

### PR DESCRIPTION
**Pull request by Shahmahdi**
### What does this PR do?
- It's making the contact page responsive on mobile, tab devices

#### Description of Task to be completed?
- The contact page is now responsive

#### How should this be manually tested?
- In the browser on multiple breakpoints

#### What are the relevant Github Issues ?
https://github.com/AgileVentures/sfn-client/issues/419

### CODE REVIEW

**Comment by aonomike** [comment]
Thanks @Shahmahdi for working on this. @javpet will review this one. Are you part of our slack already? If not you can join using through [AgileVentures](https://agileventures.org)

**Comment by javpet** [comment]
Great work @Shahmahdi ! Can you change the order, so the contact form comes first and only after the available contact info?

**Comment by Shahmahdi** [comment]
@aonomike yeah, I have joined in the slack team.
@javpet I have changed the contact form and contact info order. Please have a look at this PR.

**Review by javpet — APPROVED** [review]
Thanks for the work @Shahmahdi! 🥳

**Comment by javpet** [comment]
Fixes #419

**Comment by Shahmahdi** [comment]
> Thanks for the work @Shahmahdi! 🥳

You are welcome :)

**Pull request merged**
