### PR TITLE
[WIP] Add cypress

### LINKED ISSUE #111: Install cypress
Install cypress

We want to start connecting the frontend and backend by carving an end to end traversal of the app, using the artists as a beachhead, and a BDD, outside-in approach.

```
yarn add cypress --dev
```

https://docs.cypress.io/guides/getting-started/installing-cypress.html#yarn-add

### PR DESCRIPTION
**Pull request by aonomike**
- Add cypress as dev-dependency
Fixes #111

### CODE REVIEW

**Review by yakryder — COMMENTED** [review]
Thanks Mike!

I'm going to get right into it -- this PR has several red flags. The motivating issue #111 is a simple dependency add. 

Perfect world I would expect to see one or maybe two commits, two files changed, and fewer than 100 additions. 

This has 4 commits, 26 files changed, and 431 additions. It also has a broken build.

Can you figure out a way to make this PR -- or the #111-related work contained in it -- quieter and fix the build?

**Comment by aonomike** [comment]
Thanks @SherSpock, I am obviously adding more than the ticket mentioned :), I followed up [this simple guide](https://docs.cypress.io/guides/getting-started/installing-cypress.html#npm-install) on adding cypress to a react project while using create-react-app and running commands locally like `cypress open` to test the successful configuration generates a number of directories and files within the cypress directory. I have delete some of these. I have followed up on wso-fe implementation of cypress configuration, and that guided me to a few more changes than the ticket mentioned. I have also added it cypress to ci instead of opening another ticket to accomplish that. There were some issues with eslint and jest that needed fixing as well... I am not sure we want to do all these in different PRs or just resolve them here?

**Comment by yakryder** [comment]
@aonomike It should be done in different PRs. I would recommend moving the valuable parts of the work you've done to different branches and opening issues. The other option of course is to work with the team to modify the ticket. I see that option as dispreferred but it is certainly possible

Motivating issue #111 was just to add cypress. It even spelled out an implementation. 

In general and especially in such cases, scope should be limited to that defined in the ticket. 

If more work seems warranted, it should be discussed before doing it. 

That discussion can either happen in the ticket or happen offline and be logged to the ticket with the details and conclusion of what was discussed. 

This may seem like a headache, but unchecked scope creep and no trail of motivating factors yields bigger headaches.

In addition to the dependency adds, you've run a dependency update. In general, that should be avoided for a PR that isn't concerned with an update. It both adds noise and neglects the deliberate nature that should accompany dependency changes.

Was something about the cypress add motivating a dependency update?

**Comment by aonomike** [comment]
Thanks @SherSpock totally makes sense. Will do...

**Comment by aonomike** [comment]
We have discussed to start doing this a fresh at the #weekend-collaborations. I have therefore closed this PR and will be using it as reference to create new tickets. Thanks @SherSpock :)

**Comment by yakryder** [comment]
@aonomike Great! There's valuable work here I don't want to see lost

**Pull request closed without merging**
