### PR TITLE
Made responsive causes and artist cards

### LINKED ISSUE #237: Artist cards and Cause cards are not mobile optimized
Artist cards and Cause cards are not wrapping nicely currently on smaller/mobile devices.

## Expected Behavior

Try to find a way, to show only one card at a time, and stack them on top of each other instead of squeeze them.

## Current Behavior

The current look / implementation is not mobile-first

Screen Shot 2019-05-12 at 1 13 19 PM

### PR DESCRIPTION
**Pull request by javpet**
### What does this PR do?
- Artist cards and cause cards are responsive from mobile to desktop

#### Description of Task to be completed?
- Artist cards and cause cards should behave normally on smaller and larger devices without losing any information 

#### How should this be manually tested?

General forked repo test should work.

#### Any background context you want to provide?

Additional ticket will needed to check performance page / cards as well.

#### What are the relevant Github Issues ?

Fixes #237

### CODE REVIEW

**Comment by aonomike** [comment]
Checked this out @javpet looks really great. Please see the image below for a test I did on Galaxy S5 screen in the dev tools. Not sure if this can keep us from merging or its a quick fix? if not I am for merging this and creating another issue for the mobile phones? what do you think
Screen Shot 2019-09-22 at 10 50 00 PM
?

**Comment by javpet** [comment]
@aonomike please merge it, because the screen looks like this because of an issue with the footer, not the changes I made. We need to create a new ticket for the footer to make it responsive as well.

**Comment by aonomike** [comment]
Aaaah niiice! I will create a ticket to fix the footer issues. Thanks!

**Review by aonomike — APPROVED** [review]
Looks great @javpet Thanks!!!

**Pull request merged**
