### PR TITLE
Refactored artist card for flexible usage

### PR DESCRIPTION
**Pull request by javpet**
- Removed TrendingArtist component, and made a flexible ArtistCard component
- Refactored existing TrendinArtist tests to match ArtistCard component
- Replaced the TrendingArtist component with ArtistCard in Explore Artists and Trending Artists component
- For future usage I set an artistDetails flag on ArtistCard component to render for different purposes, I consider the artist's image and the name is a minimum for the component
- Added validation for proptypes on ArtistCard component

### CODE REVIEW

**Review by FedericoEsparza — APPROVED** [review]
@javpet Looks great, Peter!

Nice refactor, too. It'll help get us ready for injecting data to make each component unique.

I just needed to make a minor modification, because warnings were popping up in the test runner:

Screenshot 2019-04-21 13 12 26

Screenshot 2019-04-21 13 13 06

I'll go ahead and approve and merge.

Thanks for taking care of this! 🏆💯

**Comment by javpet** [comment]
Thanks @FedericoEsparza for making the change! Sorry my bad not checking the documentation, somehow I remembered boolean  🙄

**Comment by FedericoEsparza** [comment]
@javpet No problem, Peter. No need to apologize. 🙂
Thanks again for doing the work.

**Comment by FedericoEsparza** [comment]
I like the updated css.
I should post a screenshot, for the record:
Screenshot 2019-04-21 13 30 45

**Comment by yakryder** [comment]
This is good! 

I'm going to hit the `refactor` kick some more: 

The `ArtistCard` was extracted, not refactored. 

`TrendingArtist` was removed, not refactored. 

`TrendingArtists` was changed, not refactored. By populating it with `ArtistComponents` which have different values for the artistDetails supported causes and performances (6 and 3 vs 9 and 6) than the `TrendingArtist` components they replace, the user-facing behavior changed.

The `TrendingArtists` tests were not refactored. These are implementation-specific tests and what they are looking for changed. They were looking for `TrendingArtist` components, now they are looking for `ArtistCard` components. That means the dev-facing behavior of these tests has changed -- before they would fail if they didn't find the right number of `TrendingArtist` components, now they will fail if they don't find the right number of `ArtistCard` components.

I am not saying no refactor happened as part of this work. But there are many things that this PR or the closed issue are labeling refactors that (albeit one of these by a very exacting definition of the word) are not so. And precision in terms is important.

**Comment by FedericoEsparza** [comment]
@SherSpock Thanks for the additional PR discussion, Ryder.

I really like your input in terms of a learning opportunity that we can use to improve our approach; especially after the fact, since I've already merged this PR.

To be fair, Peter was away when we discussed the use of the word refactor.

**Overall, the ticket and PR was a big success,** in my opinion, because Peter said there was discussion about it in the session, when it was created. Peter was also motivated to create the ticket  and to work on it, right away, outside of the #weekend_collaboration session.

It got the job done. It was fairly documented, in the PR, and it garnered some excellent analysis from Ryder.

So I feel good about it. Thanks @javpet and @SherSpock 🙂

**Comment by yakryder** [comment]
I think it's a big win as well! 

I don't know why the use of that word to describe a restructuring in which the public behavior of the changed element also changes bothers me so much. 

But I do know why not updating the ticket bothers me. It creates space for mistakes and it's easy to fix. There are enough mistake-begetting things in development -- both difficult and impossible to fix -- that I see no reason not to continually try to do better in maintaining synchronization between the ticket and the work.

**Comment by FedericoEsparza** [comment]
✊🏼

**Pull request merged**
