### PR TITLE
Add 'How to Review a PR' documentation

### LINKED ISSUE #86: Add how to review a PR documentation
Add how to review a PR documentation

I want to empower the team to review and merge each other's tickets, so that in a weekend, you're not waiting on me to review an merge a ticket that is blocking other PRs.

This will also keep more of the team aware of a wider breadth of the codebase.

**Except for documentation PRs, it's important to run the app locally, because many times, you'll find inadvertent behavior that the CI tests won't catch.**

As a huge head start you can copy much of this document, written largely by @mattwr18, in one of his greatest PRs ever. 😁 https://github.com/championer-org/championer_one/blob/develop/devdocs/HOW-TO-REVIEW-A-DEVELOP-PR.md

That is obviously a Phoenix app that uses npm, so a lot of it will need to be altered, but here are the tl;dr commands for us:

```js
git fetch upstream
git checkout 57-artist-performance-component //for example
yarn
yarn test
// Press a to run all tests
// Press q to quit watch mode.
yarn start
// Review and inspect the app and its elements for expected and unexpected behavior
```

Also add instructions that you always want to review the **Files changed.**

You can navigate there by clicking on the tab in the PR page:

screenshot 2019-02-17 08 33 03

...or adding `/files` to the end of the PR url, for example `https://github.com/AgileVentures/sfn-client/pull/71/files`

**I prefer to view the diffs in _Unified_** form, rather than the default _Split_.

screenshot 2019-02-17 08 37 59

You can also add comments to a particular line of code, by clicking on the plus icon when you hover over a line:

screenshot 2019-02-17 08 43 51

You can then either just provide the single comment or start a review, if you haven't, yet:

screenshot 2019-02-17 08 44 40

### PR DESCRIPTION
**Pull request by dhemmingson**
Add documentation on how to review pull requests. Also added a link to the README.

Fixes #86

### CODE REVIEW

**Comment by aonomike** [comment]
@FedericoEsparza this was left specifically for you to review :)

**Review by FedericoEsparza — APPROVED** [review]
@dhemmingson @aonomike @javpet Amazing work on this PR.
You had a head start thanks to @mattwr18 but most people would have ran away from such a big documentation PR.

You guys are pros!

I just put in a PR to this PR with some minor modifications: https://github.com/AgileVentures/sfn-client/pull/108

Once someone merges it (maybe, @dhemmingson ), this one can be merged, as well.

I'll go ahead and approve!

Thanks for getting this done!! 👏

**Review by mattwr18 — APPROVED** [review]
This is awesome! very professional @dhemmingson and @FedericoEsparza... it makes a big difference for new contributors to get started quicker.

**Comment by yakryder** [comment]
Merged due to two approving reviews and all green checks/doc only change

**Pull request merged**
