### PR TITLE
Added mockup design reference

### LINKED ISSUE #28: Adding design mockup for reference for README.md

### PR DESCRIPTION
**Pull request by javpet**
Fixed #28 
- Added mockup reference to artist page

Question: do we have other mockups for the rest of the pages as well?

### CODE REVIEW

**Comment by FedericoEsparza** [comment]
@javpet Just the Edit screenflow of the Artist Profile that @vardyb created for us: https://github.com/AgileVentures/sfn-client/blob/develop/documentation/wireframes/wireframes_sfn_client.bmpr

You can download balsamiq here, to view the file: https://balsamiq.com/wireframes/desktop/ 
Let me know if you need a license, we have a couple.

**Review by FedericoEsparza — APPROVED** [review]
@javpet Thanks, Peter!
 
I'll go ahead and merge.

**Comment by javpet** [comment]
@FedericoEsparza can you please export the screen from Balsamiq and just upload underneath the other image in the README since I'm not using that app?

**Comment by javpet** [comment]
Oh also if you just send me in a DM a licence that's also fine of course!

**Pull request merged**
