### PR TITLE
chore: change header to fixed

### PR DESCRIPTION
**Pull request by bautistaaa**
### What does this PR do?
Make header sticky to top of the page

#### What are the relevant Github Issues ?
https://github.com/AgileVentures/sfn-client/issues/360

### CODE REVIEW

**Comment by javpet** [comment]
@aonomike we need to review this behavior as the stickyness might be not needed only on mobile.

**Comment by aonomike** [comment]
Thanks for working on this @bautistaaa @javpet please review...

**Comment by javpet** [comment]
My gut feeling is that we need the fixed header only for mobile. Can you please remove the sticky header for desktop @bautistaaa?

**Comment by bautistaaa** [comment]
will do @javpet!

curious why you feel its not necessary to see the header on desktop.. also which breakpoints do you consider mobile?

**Comment by javpet** [comment]
Thanks @bautistaaa ! On desktop as we estimated we'll not have the content so long that the header is required to fill up space within the browser. Of course this might change later, but to start we would like to leave as much as space open as we can. 🙂

**Comment by bautistaaa** [comment]
up to what breakpoint is considered mobile, I see the hamburger all the way up to `992px`

**Comment by javpet** [comment]
Yes, please consider it as mobile for the header until `992px` 🙂

**Comment by bautistaaa** [comment]
done! 👍

**Review by javpet — APPROVED** [review]
Great, thanks @bautistaaa !

**Comment by aonomike** [comment]
Great @javpet , many thanks @bautistaaa !!!

**Pull request merged**
