### PR TITLE
Adding the emptycard component

### LINKED ISSUE #426: Create empty card state if it doesn't receive props
Sometimes we don't have data that received from the backend. Overall we need to prepare with some empty states starting with the card.

## Expected Behavior

Adding empty states for the card component // creating an EmptyCard component

## Current Behavior

 Currently we have large spaces with empty space if we have nothing to render.

Screen Shot 2019-10-20 at 9 09 33 PM

### PR DESCRIPTION
**Pull request by javpet**
### What does this PR do?
- Adding the EmptyCard component for use cases when the API call doesn't return a card
- Added tests for EmptyCard component

#### Description of Task to be completed?
- EmptyCard component is available for use for API calls or empty states for cards

#### How should this be manually tested?

Forked repo method should be fine.

#### What are the relevant Github Issues ?

Fixes #426 

#### Screenshots (If applicable)

Screen Shot 2019-11-15 at 11 07 23 PM

### CODE REVIEW

**Review by aonomike — APPROVED** [review]
Looks good to me @javpet. Thanks for working on this!!

**Comment by javpet** [comment]
@aonomike can you please merge it in? I always freak out when I see PRs hanging in the air. ✈️

**Comment by azure-may** [comment]
Looks great!

**Comment by azure-may** [comment]
Looks great @javpet !

**Review by azure-may — COMMENTED** [review]
Looks good as is 👍

**Pull request merged**
