### PR TITLE
Added basic layout for TrendingArtist component

### LINKED ISSUE #148: Add Trending Artists summary component
Create a component that contains the summary of the Trending Artist 
## Expected Behavior

The image below shows the content of the summary component.
Screen Shot 2019-04-13 at 9 32 37 PM

### PR DESCRIPTION
**Pull request by jmpainter**
- Added basic layout and styling for the TrendingArtist component
- Moved the artist name from the ArtistImage component to the TrendingArtist parent component. I did this because I thought that the name would need to be styled according to the parent container and may not be wanted if the ArtistImage component was used elsewhere.
- In the TrendingArtists container, the h1 and TrendingArtist components are being laid out according to the parent 12 column grid instead of the existing flexbox container. I believe this to be the intended use of the grid layout for the site.

fixes #148

### CODE REVIEW

**Comment by aonomike** [comment]
Thanks for working on this @jmpainter and much more for fixing the css!! There are however some failing tests that maybe you want to run locally and fix maybe?
Also, I have edited the comment to add the `fixes#148` for use by the wafflebot. 
I have also tagged some reviewers :)

**Comment by jmpainter** [comment]
Great - I added  to the PR to fix the tests

**Comment by jmpainter** [comment]
Ok, great - I updated this PR to fix ArtistImage.test.

**Review by arku — APPROVED** [review]
LGTM :100:

**Review by FedericoEsparza — APPROVED** [review]
@jmpainter Excellent work!

Looks amazing!
Screenshot 2019-04-16 13 16 24

Thanks for jumping right in and making a big impact with this PR. 

Really appreciate it. I'll go ahead and approve and merge.

**Pull request merged**
