### PR TITLE
208 add causes carousel

### LINKED ISSUE #208: Add Causes Carousel
On the `cause/:id` page, add a Carousel that displays images about the cause. 
## Expected Behavior

A slide show with images about the Cause. See image below 
Screen Shot 2019-05-05 at 8 21 23 PM

## Current Behavior

The CauseImages carousel component has not been created yet
## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by javpet**
Fixes #208 

- Added CauseCarousel component with tests
- Added small styling changes on CauseBioDetail to align with CauseCarousel
- Added tests to CauseBio to test CauseCarousel

*the implementation is not 100% since the carousel jumps one step further than the last image showing a dark-blie, and also similarly jumps one step further on the last image, please have a look at the implementation. Probably something can be played around with the rendering / state, couldn't figure it out. :(

### CODE REVIEW

**Comment by javpet** [comment]
Screen Shot 2019-05-11 at 1 57 35 PM

**Review by FedericoEsparza — APPROVED** [review]
@javpet Beautiful work, Peter.

Really impressed by this.

I fixed the carousel switching. You can see the diff [here](https://github.com/AgileVentures/sfn-client/pull/222/commits/d8860a0563e406c9018bfc40ce7d86997d96df29)

I'll go ahead and merge!

Thanks for working on this. 🏆

**Comment by javpet** [comment]
Thanks Federico for fixing the issue! I had a similar implementation at first, then I tried to simplify that and lost the old code, that's the moment it went wrong. 😅

**Comment by FedericoEsparza** [comment]
😁

**Pull request merged**
