### PR TITLE
Add TrendingArtist component

### LINKED ISSUE #76: Add trending artist component
Add trending artist component

screenshot 2019-02-16 11 59 11

Let's call these `TrendingArtist`. They're the individual components inside the list.

### PR DESCRIPTION
**Pull request by aonomike**
Fixes #76

### CODE REVIEW

**Review by dhemmingson — APPROVED** [review]
Worked on this with @aonomike , so looks good to me!

**Review by FedericoEsparza — COMMENTED** [review]
@aonomike @dhemmingson Great work on these. 

I do have some request for changes. I'll just submit as a comment, though, so you can merge sooner, if needed.

There might still be some lingering confusion about the container/component folder structure, so I made a diagram that I hope will help clear up matters:

Screenshot 2019-04-08 00 02 06

Please modify accordingly.

**Also, please refactor the TrendingArtist into a functional component, since it's NOT a container.**

You're making excellent progress. Thanks for your overtime contributions!! 💪

**Comment by mattwr18** [comment]
I saw this on #weekend_collaborations!! loving your draw.io skills @FedericoEsparza!!!
it really helps to have visuals

**Comment by FedericoEsparza** [comment]
Thanks @mattwr18 . If I'm being modest, I'd say I'm quite good at it. 😁 Thanks for the compliment!!

**Pull request merged**
