### PR TITLE
Closing mobile menu on body click

### LINKED ISSUE #269: make mobile menu close by clicking on page body
Make mobile menu close by clicking on page body

## Expected Behavior
Make mobile menu close by clicking outside the mobile menu.

## Current Behavior
You have to click on the hamburger menu.

## Possible Solution
This might take some trial and error to get working perfectly. Reach out if you get stuck.

### PR DESCRIPTION
**Pull request by javpet**
### What does this PR do?
 - Added functionality to mobile header to close, when user clicks / taps outside of the menu
 - Added "X" on mobile header to represent the closing behavior

#### Description of Task to be completed?
- The mobile menu should be closed, when user is tapping clicking outside of the menu area or tapping the "X" icon

#### How should this be manually tested?

The regular way of testing forked repos should be enough.
https://github.com/AgileVentures/sfn-client/blob/develop/HOW-TO-REVIEW-A-DEVELOP-PR.md#for-forked-repos

Go to the mobile viewport and the try to open / close the menu with the methods mentioned above!

#### What are the relevant Github Issues ?
Fixes #269

### CODE REVIEW

**Comment by okothkongo** [comment]
though not necessary a screenshot or gif would do for visualization

**Comment by javpet** [comment]
@okothkongo1 if you're going through checking the PR review process you'll eventually see the solution, but I'll try to attach the video I made. :)

Mobile_menu

**Comment by okothkongo** [comment]
:+1:  nice job

**Review by okothkongo — APPROVED** [review]
job well  done @javpet

**Pull request merged**
