### PR TITLE
Setup eslint and husky

### LINKED ISSUE #113: Adding JS linter to code consistency
As more and more people start touching the project we might need some rules on code formats and styling so maybe we can use some kind of linter?

### PR DESCRIPTION
**Pull request by arku**
Closes #113

Stuff done:

- Sets up eslint, makes use of [Standard config](https://github.com/standard/eslint-config-standard). We can add another config if the team gets to consensus. 
**Note**: I had to install `eslint@5.6.0` as `react-scripts` was complaining about incompatible eslint versions when I installed the latest version.
- Fixes eslint errors.
- Adds [husky](https://www.npmjs.com/package/husky) and sets up a pre-commit hook to run `eslint` before commiting a change.
- Removes 'component renders without crashing' tests as those don't add a lot of value. Feel free to discuss if you want to add those tests back.

Sorry for a bunch of changes introduced in the PR :see_no_evil: . Most of them are cosmetic I assure.

### CODE REVIEW

**Review by FedericoEsparza — CHANGES_REQUESTED** [review]
@arku This is a great endeavor. Thanks for taking the time to work on it.

**Can I ask you to please re-add the initial tests that you removed, and create a separate issue and PR for removing them?**

You're right in that they don't add much, at this point.

However, I want the team to make it a practice to make smaller PRs where possible, and not engage in issue (scope) creep, where a PR makes unrelated changes.

**The smaller in scope that the PRs are, the more likely that they are to be reviewed carefully and merged faster by anyone on the team.**

And don't feel bad about having to re-add these tests.

I asked some of the rest of the team to re-add them in an earlier PR, out of principle there too.
 
**_tl;dr: replacing your whole test suite in one PR is dangerous._** 

The following is a [comment from that other PR](https://github.com/AgileVentures/sfn-client/pull/100#discussion_r266212136): 
> **I believe the whole current test suite is removed within this PR, which is not good practice, because then replacing it with a simple test, like the following:**
> 
> ```
> expect(1+1).toEqual(2)
> ```
> or something else meaningless, like that, could pass the CI and get merged in, if no one is reviewing the PRs properly.

It's easy to create an it function (a test), in javascript, that passes in your test runner, without actually testing anything, so it was important to have a constant while adding the more meaningful enzyme tests, rather than replacing all the tests at once.

The tests were used for helping to setup the CI and to introduce testing without overwhelming those who were new to React, and to help expand the test suite to every component.

They can be removed now, _in a separate PR._ 😁

**Comment by yakryder** [comment]
@arku Sorry, didn't notice you had tagged me for review til now. 

Overall, this is positive work that addresses #113. Whether #113 meets Definition of Ready as a ticket is an [open question](https://github.com/AgileVentures/sfn-client/issues/121). 

I agree with the iddy biddy PR principle. 

For example with this one, #113 effectively said let's add a linter, which is one thing. This PR does the following four things:

- adds a linter 
- fixes up the project to be in compliance with said linter
- adds a pre-commit enforcer of said linter 
- removes a bunch of tests

That is debatably way beyond the scope outlined in the motivating ticket. If the project had a DoR and the motivating ticket were in compliance with that DoR, that may have helped head off this kind of scope creep.

In terms of the git history, this PR is a shotgun blast. When linters get added to projects or significant rules get changed whose ripples travel through the entire project, there are a couple ways to approach it which you're probably familiar with. 

One is to just get it over with and roll the changes in when the linter is added.  I dislike that approach because it's so noisy. 

I'd prefer to see files come under compliance either in isolated or manageably bundled PRs, or as they are modified due to relevant work. 

Naturally making style changes to satisfy the linter while you are touching a file for other reasons increases the scope of the relevant PR rather than isolating a PR to strictly linter changes. Those tradeoffs are up to the working dev to reason through. 

In order for the pre-commit linting hook to go in with this PR, the whole project had to be made compliant. I would prefer to have sees the PR keep with the less invasive scope roughly outlined in motivating issue #113 and see files brought under compliance through other work specifically motivated by tickets that meet a project Definition of Ready. 

I won't attempt to insist on it though! Especially so early project. 

I do agree it would be better for the tests to be put back. They were removed in a commit that is unrelated and doesn't even describe their removal, in a PR that is similarly unrelated. That's several things that arguably shouldn't be done. If the test change had been left atomic to a single commit with a descriptive message, reverting the change would be as simple as reverting the commit.

I'm not saying there are no counterarguments and I'm open to hearing them in Slack or hangouts. Here on I think we should focus on making the PR scope make sense, minimally by putting back those tests. 

No one is fervently arguing for the tests to stick around. But if they go, it seems better that they be removed clearly and deliberately.

**Comment by FedericoEsparza** [comment]
@SherSpock Thanks so much for adding your review. I agree with you completely.

I am concerned about demotivating @arku and having him do too much work and deal with too many merge conflicts.

I do typically like to try to merge PRs, as they're ready, in the order that they come in, without any rebasing, as it tends to decrease the likelihood of merge conflicts.

Merge conflicts have the potential to slow down progress and discourage volunteers.

In terms, of the shotgun blast and git history. I would prefer that the actual lint fixes not all be done at the same time, as you described. However, it's not the worst thing for them to all be fixed at once, in this `Setup eslint and husky` PR. It would be unacceptable if they were done all at once in some completely unrelated PR, like a documentation PR.

As I mentioned in a comment on the `Removed components rendering without crashes tests...` #128 , merging it would bring this PR into compliance faster.

**I'd be willing to work through the merge conflicts on #128 and merge it, if you lift your request for changes (i.e. Approve changes), then work through the merge conflicts here, just to get this out of the way.**

I think momentum and developer happiness takes precedence, in this situation, especially since we've already significantly highlighted the issue, and taken steps to avert it, going forward, thanks to your help, Ryder.

**Comment by yakryder** [comment]
@FedericoEsparza Just seeing this. I can lift the request for changes, but I disagree with effectively letting this slide. 

There should have been discussion on #113 before the PR solving that issue had its scope expanded to include linting the files and adding a precommit hook. 

Adding the precommit hook without any real discussion or consensus on linting rules -- and when the linter itself is a net new for the project -- is skipping one or more feedback cycles. It does not seem to be advisable.

Wasting the tests now being removed in #128 as part of a linting PR was similarly a procedural gaffe. Saying "OK we'll merge it anyway" sends the message that following good process is optional. 

(As an aside, we recently have some instances of new admins just merging things without an apparent formal review process. If devs are feeling blocked or stymied by too much PR overhead, that discussion should be making its way to the perceived blockers. If devs are instead just choosing not to do a formal review at all, that's a discussion point.)

You mentioned developer happiness as a motive for merging. I would assert for your consideration that developer happiness almost *never* comes from letting developers just do what they want. That's a good recipe for poor process, resentments, and ultimately an unhealthy project from both a team and technical perspective. 

This is about bad process, the calling out of which should never be taken personally or as a cause for unhappiness.

**Comment by yakryder** [comment]
@FedericoEsparza Am realizing you were requesting waving the change request on #128, not here. Standing by the other points made here, that is now done.

**Review by FedericoEsparza — APPROVED** [review]
@arku Amazing work, Arun!
Thanks so much for getting this done!

This will add consistency to our code.

We now have `yarn lint:fix`, by the way, anyone else reading this.

**Pull request merged**
