### PR TITLE
151 add icons to causes and artists

### LINKED ISSUE #151: Add icons to Supported Causes and Related Artists
## Expected Behavior

Add icons to Supported Causes and Related Artists list items on the Artist page.
Screen Shot 2019-03-31 at 10 26 19 AM

## Current Behavior

Currently there are no icons:
no-icons

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by jmpainter**
- Added react-fontawesome
- Added icons for Related Artists and Supported Causes
- set width to 100% for these components to accommodate
- changed RelatedArtists h3 to Related Artists
- updated test for ReleatedArtists

fixes #151

### CODE REVIEW

**Comment by arku** [comment]
#### Screenshot

image

**Review by arku — APPROVED** [review]
A minor thing. What do you think of adding a bit more spacing between the icon and the text?

LGTM :+1:

**Comment by jmpainter** [comment]
I added a className for the icons and set more spacing around the icons and list items.

**Review by FedericoEsparza — COMMENTED** [review]
@jmpainter Nice work, Joshua. Appreciate your super fast modifications!

**Review by FedericoEsparza — APPROVED** [review]
@jmpainter Great work on getting us set up with fontawesome and tweaking the css!

Looks great!

I'll go ahead and merge.

Thanks!

**Comment by FedericoEsparza** [comment]
@arku Thanks, Arun, for keeping your eye on this PR and for reviewing it.
That's very helpful!

**Pull request merged**
