### PR TITLE
removing port from start script in package.json

### LINKED ISSUE #158: Remove specific PORT
Remove specific PORT for `start` script.

In `package.json`, revert to default create-react-app version:
```
    "start": "react-scripts start",
```

Also update the documentation:
https://github.com/AgileVentures/sfn-client/search?q=8081&unscoped_q=8081

It's giving Windows users trouble.

The original need for it was for mob developing on c9. However, other than the initial 1 or 2 sessions, there haven't been any mob programming on c9 for the project, due to the advent of VSCode Live Share.

Plus c9, in its current state, is going away.

### PR DESCRIPTION
**Pull request by jmpainter**
Thanks for requesting this change - Specifying the port at the beginning of the start script is an issue on Windows, it could be put in an .env file if needed in the future

fixes #158

### CODE REVIEW

**Comment by FedericoEsparza** [comment]
@jmpainter Could you also please update the documentation, Josh?
See here:
https://github.com/AgileVentures/sfn-client/search?q=8081&unscoped_q=8081

**Comment by jmpainter** [comment]
HOW-TO-REVIEW-A-DEVELOP-PR.md - changed references to port 8081 to 3000

**Review by arku — APPROVED** [review]
LGTM :100:

**Comment by yakryder** [comment]
Mostly I agree with @arku.

There's seven commits. What do you think of using some kind of squash to keep the history closer to the scope of the work?

**Review by yakryder — COMMENTED** [review]
Changes look good. It's the history I'm asking about

**Comment by jmpainter** [comment]
Sorry for the late response, I had mistakenly thought that your question was posed to @arku. From my understanding, in this project it is preferred to rebase vs. squash.

**Comment by yakryder** [comment]
@jmpainter No apology needed -- I think I should have added an explicit mention for you as well to reduce the probability of the comment being lost.

Yeah, squashing is dispreferred on this project. @FedericoEsparza  and I disagree on squashing, which is fine -- he and I talked it over last week and came to an agreement depending on what you decided to do next. You declined the squash so that'll be what we go with.

**Review by yakryder — APPROVED** [review]

**Comment by yakryder** [comment]
When I say squash, I'm probably not being precise enough -- I mean a rebase where the noise is dropped via `squash` or `fixup`

I agree with no squashing inasmuch as I don't think this project should have squashed PRs. 

I also strongly prefer atomic and descriptively named commits like the ones you've included because I think they promote a clean and intelligible git history. 

But I'd argue that this many commits for such a simple change is noise, and it doesn't seem to me that preserving that noise in the history nets us anything. 

A fixup would clean the noise up pretty easily

**Comment by jmpainter** [comment]
I agree with you, this PR ended up with an unnecessary number of commits. The --fixup approach sounds good, hadn't heard of it until now.

**Comment by FedericoEsparza** [comment]
TO BE CLEAR: Please DON'T rebase on this project. 🙂

**Pull request merged**
