### PR TITLE
Convert ArtistPerformance to functional component

### PR DESCRIPTION
**Pull request by chrisdesilva**
Updated ArtistPerformance.js file

### CODE REVIEW

**Comment by yakryder** [comment]
@chrisdesilva This duplicates #146. As you know, if you assign yourself to an issue when you start working it, the probability of duplicate work plummets

**Comment by yakryder** [comment]
Between this and #146 I would vote for this one. The changes seem to me to be less noisy and we are using the word 'convert', which it seems to me is much clearer here than refactor. 

Changing from a class component to a functional one alters the public API of the ArtistPerformance class. That alters its potential -- and in this case, its actual -- behavior. That this change is undetectable by a user of the system seems to me to be irrelevant. 

I assert the school of thought here that the word refactor should be reserved for changes that do not effect behavior, and that it seems to me that this keeps most closely with the intended and conventional usage of the word.

**Comment by chrisdesilva** [comment]
@SherSpock thanks for the feedback. Still getting my feet wet with contributing to open source projects, so I didn't know about the ability to assign yourself to an issue. Let me know if there is anything else I can do to help with this component.

**Comment by yakryder** [comment]
@chrisdesilva Oh, great! Teachable moment. Duplicate work is a small thing when the work items are small, but I think it's important to follow good habits all the time, except when the context might cause their application to be dogmatic and counter-productive.

**Comment by yakryder** [comment]
Thanks for putting this together.

**Review by yakryder — COMMENTED** [review]
Looks clean and simple to me. I have looked at the code -- I have not pulled, run, or observed.  Can someone better versed in React take an additional quick look

**Comment by yakryder** [comment]
@arku What do you think? Do you think this is missing anything critical that #146 has?

**Review by FedericoEsparza — APPROVED** [review]
@chrisdesilva  Nice job! Looks good.
 
I'll go ahead and merge.
 
You're welcome to join us at [agileventures.org](https://www.agileventures.org/users/sign_up), as we continue to build the site, and work on building other open source Elixir/Phoenix/React projects. 
 
If you sign up via your github account, you'll get an invitation to our Slack. Here's our team's [AgileVentures.org Slack channel](https://agileventures.slack.com/messages/phoenix_one)
 
There's also a LIVE group coding session, starting in a few minutes, that you're most welcome to join or watch [here](https://www.agileventures.org/events/weekendcollaborations-413b50c9-2f64-4a6f-aeb2-3c26e2263665).

Thanks again!

**Pull request merged**
